# Generated by Django 2.0 on 2017-12-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_src', models.CharField(default='', max_length=20)),
                ('lang_tgt', models.CharField(default='', max_length=20)),
                ('record_src', models.TextField(default='')),
                ('record_tgt', models.TextField(default='')),
            ],
        ),
    ]
